/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package petstoreapp;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.PersistenceUnit;
import javax.persistence.EntityManager;

import com.Customer;
import com.CustomerId;
import com.Person;
import com.PetStore;
import com.EmployeeId;
import com.Employee;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    //private static EntityManager entityManager;
    public static void main(String args[])
    {
    	System.out.println("###########################");
    	System.out.println("Java Persistence API");
    	System.out.println("########################");
    	EntityManagerFactory emf=Persistence.createEntityManagerFactory("PetPU");
    	EntityManager entityManager=emf.createEntityManager();
   
       EmployeeId id=new EmployeeId();
       id.setEmployeeEmail("peter@gmail.com");
       id.setEmployeeId(1);

        Employee obj=new Employee();
    	 obj.setId(id);
    	 obj.setEmployeeName("Jason");
    	 obj.setAddress("55 old streer");
        
    	entityManager.getTransaction().begin();
    	entityManager.persist(obj);
    	entityManager.flush();
    	entityManager.getTransaction().commit();
    	
    	
    	
    	
    }
    
}
