/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smapledemo1;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String args[])
    {
    	System.out.println("#################################");
    	System.out.println("Java Persistence API");
    	System.out.println("###################################");
    	EntityManagerFactory factory= Persistence.createEntityManagerFactory("StudentPU");
    	EntityManager entityManager=factory.createEntityManager();
        try {
        	 entityManager.getTransaction().begin();
        	 Student obj=new Student();
        	 obj.setId(1);
        	 obj.setStudentName("Peter");
        	 obj.setAddress("23 baker street");
        	 entityManager.persist(obj);
        	 entityManager.flush();
        	    entityManager.getTransaction().commit();
        	
        }
        catch(Exception e)
        {
        	
        }
    	 
    }
}
