/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PracticeQuestionSolutions;
import com.*;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import java.util.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String args[])
    {
          	EntityManagerFactory factory=Persistence.createEntityManagerFactory("PracticePU");
          	EntityManager manager=factory.createEntityManager();
          	
          	
          	Person obj=new Person();
          	obj.setPersonName("Jacob");
          	obj.setPersonAddress("23 old baker street");
          	
          	
          	
          	
          	
          	
          	manager.getTransaction().begin();
         
           manager.flush();
           manager.getTransaction().commit();
           
    }
}
